apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: sse-relay-demo
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      components:
        - name: sse-relay
          image: wasmcloud-registry:5000/sse-relay:0.1.0
          localResources:
            environment:
              config:
                OPENAI_API_KEY: "CHANGE_ME"
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - incoming-handler
            - outgoing-handler
          config:
            host: sse-relay-demo
