apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: sse-demo
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      service:
        image: wasmcloud-registry:5000/sse-service:0.1.0
        maxRestarts: 3
        localResources:
          environment:
            config:
              SSE_BIND_ADDR: "127.0.0.1:9090"
      components:
        - name: sse-gateway
          image: wasmcloud-registry:5000/sse-http-gateway:0.1.0
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - incoming-handler
          config:
            host: sse-demo
